# Introduction to PyTorch Tensors

This notebook is referenced from the second video in the [PyTorch Beginner Series](https://www.youtube.com/playlist?list=PL_lsbAsL_o2CTlGHgMxNrKhzP97BaG9ZN) by Brad Heintz on YouTube. The video focuses on the basic concepts in PyTorch that are used to handle several deep learning tasks and demonstrates how these concepts come together to make PyTorch a robust machine learning framework. You can find the notebook associated with the video [here](https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html).


In [1]:
# Import libraries here
import math

import numpy as np
import torch

## Creating Tensors

The different ways of creating a PyTorch tensor are as follows:

- torch.empty - allocates the required memory, does not initialize values.
- torch.zeros - initializes a tensor filled with zeros.
- torch.ones - initializes a tensor filled with ones.
- torch.rand - initializes a tensor filled with random values.
- torch.tensor - initializes a tensor with the input values.
- torch.from_numpy - initializes a tensor with a numpy array.


In [2]:
# Create an empty tensor
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [3]:
# Create a zeros tensor
zeros = torch.zeros(2, 3)
print(f'Zeros Tensor:\n{zeros}\n')

# Create a ones tensor
ones = torch.ones(2, 3)
print(f'Ones Tensor:\n{ones}\n')

# Create a random tensor
torch.random.manual_seed(42)
random = torch.rand(2, 3)
print(f'Random Tensor:\n{random}')

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random Tensor:
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [4]:
# Allocate memory for a tensor
x = torch.empty(1, 2, 3)
print(f'Original Tensor:\n{x.shape}\n{x}\n')

# Allocate another memory space similar to x
empty_like_x = torch.empty_like(x)
print(f'Similar Tensor:\n{empty_like_x.shape}\n{empty_like_x}\n')

# Create a similar zeros tensor
zeros_like_x = torch.zeros_like(x)
print(f'Zeros Tensor:\n{zeros_like_x.shape}\n{zeros_like_x}\n')

# Create a similar ones tensor
ones_like_x = torch.ones_like(x)
print(f'Ones Tensor:\n{ones_like_x.shape}\n{ones_like_x}]\n')

# Create a similar random tensor
random_like_x = torch.rand_like(x)
print(f'Random Tensor:\n{random_like_x.shape}\n{random_like_x}')

Original Tensor:
torch.Size([1, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

Similar Tensor:
torch.Size([1, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

Zeros Tensor:
torch.Size([1, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

Ones Tensor:
torch.Size([1, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]]])]

Random Tensor:
torch.Size([1, 2, 3])
tensor([[[0.2566, 0.7936, 0.9408],
         [0.1332, 0.9346, 0.5936]]])


In [5]:
# Create a constant tensor
constants = torch.tensor([[math.pi, math.e], [1, 2]])
print(f'Constant Tensor:\n{constants}')

Constant Tensor:
tensor([[3.1416, 2.7183],
        [1.0000, 2.0000]])


In [6]:
# Create a tensor with 16-bit integers
a = torch.ones((2, 3), dtype=torch.int16)
print(f'Tensor `a`:\n{a}\n')

# Create a tensor with 64-bit floating-point numbers
b = torch.rand((2, 3), dtype=torch.float64) * 10
print(f'Tensor `b`:\n{b}\n')

# Convert b to 32-bit integers
c = b.to(torch.int32)
print(f'Tensor `c`:\n{c}')

Tensor `a`:
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

Tensor `b`:
tensor([[9.5524, 9.2875, 0.8354],
        [1.3264, 1.5705, 3.7537]], dtype=torch.float64)

Tensor `c`:
tensor([[9, 9, 0],
        [1, 1, 3]], dtype=torch.int32)


## Applying Tensor Operations

The various operations that can be applied to tensors are as follows:

- Basic arithmetic operations
- Common element-wise functions
- Trignometric functions
- Element-wise bitwise operations
- Comparison operations
- Reduction/Aggregation operations
- Vector and matrix operations
- Alter tensors in place
- Outputting operations in tensors
- Cloning a tensor (with or without autograd)
- Moving the tensor to GPU


In [7]:
# Set a size for the tensors
size = (3, 3)

# Create a ones tensor
ones = torch.ones(size)
print(f'Ones Tensor:\n{ones}\n')

# Create a twos tensor
twos = torch.ones(size) * 2
print(f'Twos Tensor:\n{twos}\n')

# Create a threes tensor
threes = ones + twos
print(f'Threes Tensor:\n{threes}\n')

# Create a fours tensor
fours = twos ** 2
print(f'Fours Tensor:\n{fours}')

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Twos Tensor:
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

Threes Tensor:
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

Fours Tensor:
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [8]:
# Create a tensor filled with sqrt(2)
sqrt2s = twos ** 0.5
print(f'Sqrt2s Tensor:\n{sqrt2s}\n')

# Create a tensor filled with 2^x
powers2 = twos ** torch.arange(np.prod(size)).view(size)
print(f'Powers2 Tensor:\n{powers2}\n')

# Create a dozens tensor
dozens = threes * fours
print(f'Dozens Tensor:\n{dozens}')

Sqrt2s Tensor:
tensor([[1.4142, 1.4142, 1.4142],
        [1.4142, 1.4142, 1.4142],
        [1.4142, 1.4142, 1.4142]])

Powers2 Tensor:
tensor([[  1.,   2.,   4.],
        [  8.,  16.,  32.],
        [ 64., 128., 256.]])

Dozens Tensor:
tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])


In [9]:
# Generate a random tensor and create a mapping
torch.manual_seed(42)
x = torch.rand(2, 4)
y = 2 * x - 1
print(f'Tensor `x`:\n{x}\n')
print(f'Tensor `y`:\n{y}\n')
print('Tensor `x` is mapped to Tensor `y`\n')

# Apply common functions
print(f'Absolute value of `y`:\n{torch.abs(y)}\n')
print(f'Ceiling value of `y`:\n{torch.ceil(y)}\n')
print(f'Flooring value of `y`:\n{torch.floor(y)}\n')
print(f'Tensor `y` clamped to [-0.5, 0.5]:\n{torch.clamp(y, -0.5, 0.5)}')

Tensor `x`:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])

Tensor `y`:
tensor([[ 0.7645,  0.8300, -0.2343,  0.9186],
        [-0.2191,  0.2018, -0.4869,  0.5873]])

Tensor `x` is mapped to Tensor `y`

Absolute value of `y`:
tensor([[0.7645, 0.8300, 0.2343, 0.9186],
        [0.2191, 0.2018, 0.4869, 0.5873]])

Ceiling value of `y`:
tensor([[1., 1., -0., 1.],
        [-0., 1., -0., 1.]])

Flooring value of `y`:
tensor([[ 0.,  0., -1.,  0.],
        [-1.,  0., -1.,  0.]])

Tensor `y` clamped to [-0.5, 0.5]:
tensor([[ 0.5000,  0.5000, -0.2343,  0.5000],
        [-0.2191,  0.2018, -0.4869,  0.5000]])


In [10]:
# Setup a tensor for various angles - [0, 2\pi]
angles = torch.linspace(0., 2 * math.pi, np.prod(size)).view(size)

# Apply trignometric functions
sines = torch.sin(angles)
print(f'Angles:\n{angles}\n')
print(f'Sines of angles:\n{sines}\n')
print(f'Sine inverses for angles:\n{torch.asin(sines)}')

Angles:
tensor([[0.0000, 0.7854, 1.5708],
        [2.3562, 3.1416, 3.9270],
        [4.7124, 5.4978, 6.2832]])

Sines of angles:
tensor([[ 0.0000e+00,  7.0711e-01,  1.0000e+00],
        [ 7.0711e-01, -8.7423e-08, -7.0711e-01],
        [-1.0000e+00, -7.0711e-01,  1.7485e-07]])

Sine inverses for angles:
tensor([[ 0.0000e+00,  7.8540e-01,  1.5708e+00],
        [ 7.8540e-01, -8.7423e-08, -7.8540e-01],
        [-1.5708e+00, -7.8540e-01,  1.7485e-07]])


In [11]:
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])

# Apply bitwise operations
print(f'Tensor `b`:\n{b}\n')
print(f'Tensor `c`:\n{c}\n')
print(f'NOT `b`:\n{torch.bitwise_not(b)}\n')
print(f'NOT `c`:\n{torch.bitwise_not(c)}\n')
print(f'`b` AND `c`:\n{torch.bitwise_and(b, c)}\n')
print(f'`b` OR `c`:\n{torch.bitwise_or(b, c)}\n')
print(f'`b` XOR `c`:\n{torch.bitwise_xor(b, c)}')

Tensor `b`:
tensor([ 1,  5, 11])

Tensor `c`:
tensor([ 2,  7, 10])

NOT `b`:
tensor([ -2,  -6, -12])

NOT `c`:
tensor([ -3,  -8, -11])

`b` AND `c`:
tensor([ 0,  5, 10])

`b` OR `c`:
tensor([ 3,  7, 11])

`b` XOR `c`:
tensor([3, 2, 1])


In [12]:
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)

# Apply comparison operations
print('Is `d` == `e`?')
print(torch.eq(d, e))

Is `d` == `e`?
tensor([[ True, False],
        [False, False]])


In [13]:
f = torch.tensor([1, 2, 1, 2, 1, 2, 3])

# Apply reduction operations
print(f'Maximum value in `d`:\n{torch.max(d)}\n')
print(f'Average value of `d`:\n{torch.mean(d)}\n')
print(f'Standard deviation of `d`:\n{torch.std(d)}\n')
print(f'Product of all values in `d`:\n{torch.prod(d)}\n')
print(f'The unique values in `f`:\n{torch.unique(f)}')

Maximum value in `d`:
4.0

Average value of `d`:
2.5

Standard deviation of `d`:
1.29099440574646

Product of all values in `d`:
24.0

The unique values in `f`:
tensor([1, 2, 3])


In [14]:
# Define some vectors
v1 = torch.tensor([1., 0., 0.])
v2 = torch.tensor([0., 1., 0.])

# Apply vector operations
print(f'Vector `v1`:\n{v1}\n')
print(f'Vector `v2`:\n{v2}\n')
print(f'Cross product of `v1` with `v2`:\n{torch.cross(v1, v2, dim=0)}\n')
print(f'Cross product of `v2` with `v1`:\n{torch.cross(v2, v1, dim=0)}')

Vector `v1`:
tensor([1., 0., 0.])

Vector `v2`:
tensor([0., 1., 0.])

Cross product of `v1` with `v2`:
tensor([0., 0., 1.])

Cross product of `v2` with `v1`:
tensor([ 0.,  0., -1.])


In [15]:
# Define some matrices
m1 = torch.rand(2, 2)
m2 = torch.tensor([[3., 0.], [0., 3.]])     # (Identity matrix) * 3
m3 = torch.matmul(m1, m2)

# Apply matrix and linear algebra operations
print(f'Matrix `m1`:\n{m1}\n')
print(f'Matrix `m2`:\n{m2}\n')
print(f'Matrix multiplication of `m1` with `m2`:\n{m3}\n')
print(f'Singular value decomposition of `m3`:\n{torch.svd(m3)}')

Matrix `m1`:
tensor([[0.9408, 0.1332],
        [0.9346, 0.5936]])

Matrix `m2`:
tensor([[3., 0.],
        [0., 3.]])

Matrix multiplication of `m1` with `m2`:
tensor([[2.8223, 0.3996],
        [2.8038, 1.7807]])

Singular value decomposition of `m3`:
torch.return_types.svd(
U=tensor([[-0.6457, -0.7636],
        [-0.7636,  0.6457]]),
S=tensor([4.2808, 0.9123]),
V=tensor([[-0.9258, -0.3779],
        [-0.3779,  0.9258]]))


In [16]:
# Altering tensors in place
g = torch.tensor(np.linspace(0., 3 * math.pi / 4, 4))
print(f'Tensor `g` before applying sine:\n{g}\n')
print(f'Applying sine to `g`:\n{torch.sin_(g)}\n')
print(f'Tensor `g` after applying sine:\n{g}')

Tensor `g` before applying sine:
tensor([0.0000, 0.7854, 1.5708, 2.3562], dtype=torch.float64)

Applying sine to `g`:
tensor([0.0000, 0.7071, 1.0000, 0.7071], dtype=torch.float64)

Tensor `g` after applying sine:
tensor([0.0000, 0.7071, 1.0000, 0.7071], dtype=torch.float64)


In [17]:
p = torch.rand(2, 2)
q = torch.rand(2, 2)
r = torch.zeros(2, 2)

# Using the `out` parameter
print(f'Tensor `r` before:\n{r}\n')
s = torch.matmul(p, q, out=r)
print(f'Tensor `r` after:\n{r}\n')
print(f'Tensor `s`:\n{s}\n')
print(f'Is `r` same as `s`? {r is s}')

Tensor `r` before:
tensor([[0., 0.],
        [0., 0.]])

Tensor `r` after:
tensor([[0.9211, 0.8552],
        [0.7707, 0.6947]])

Tensor `s`:
tensor([[0.9211, 0.8552],
        [0.7707, 0.6947]])

Is `r` same as `s`? True


In [18]:
u = torch.ones(2, 2)
v = u.clone()   # Cloning tensor `u`
print('~ Before mutating the tensor ~\n')
print(f'Tensor `u`:\n{u}\n')
print(f'Tensor `v`:\n{v}\n')
print(f'Is `u` == `v`?\n{torch.eq(u, v)}\n')

# Mutating the original tensor
u[0][1] = 54
print(f'~ After mutating the tensor ~\n')
print(f'Tensor `u`:\n{u}\n')
print(f'Tensor `v`:\n{v}\n')
print(f'Is `u` == `v`?\n{torch.eq(u, v)}')

~ Before mutating the tensor ~

Tensor `u`:
tensor([[1., 1.],
        [1., 1.]])

Tensor `v`:
tensor([[1., 1.],
        [1., 1.]])

Is `u` == `v`?
tensor([[True, True],
        [True, True]])

~ After mutating the tensor ~

Tensor `u`:
tensor([[ 1., 54.],
        [ 1.,  1.]])

Tensor `v`:
tensor([[1., 1.],
        [1., 1.]])

Is `u` == `v`?
tensor([[ True, False],
        [ True,  True]])


In [19]:
# Turn on autograd
i = torch.rand(2, 2, requires_grad=True)
print(f'Tensor `i`:\n{i}\n')

# Clone the tensor `i` with autograd
j = i.clone()
print(f'Tensor `j`:\n{j}\n')

# Clone the tensor `i` without autograd
k = i.detach().clone()
print(f'Tensor `k`:\n{k}')

Tensor `i`:
tensor([[0.2696, 0.4414],
        [0.2969, 0.8317]], requires_grad=True)

Tensor `j`:
tensor([[0.2696, 0.4414],
        [0.2969, 0.8317]], grad_fn=<CloneBackward0>)

Tensor `k`:
tensor([[0.2696, 0.4414],
        [0.2969, 0.8317]])


In [20]:
# Check if GPU is available
if torch.cuda.is_available():
    curr_device = torch.device('cuda')
else:
    curr_device = torch.device('cpu')
print(f'Current Device: {curr_device}\n')

# Creating a tensor on the current device
z = torch.rand(2, 2, device=curr_device)
print(f'Tensor `z`:\n{z}')

Current Device: cpu

Tensor `z`:
tensor([[0.1053, 0.2695],
        [0.3588, 0.1994]])


## Manipulating the Tensor Shapes

The various ways to change tensor shapes are as follows:

- unsqueeze - adds a 1-dim to the tensor.
- squeeze - removes a 1-dim from the tensor.
- reshape - reshapes the tensor to the desired shape.


In [21]:
a = torch.rand(3, 3, 3)
print(f'Tensor `a` before unsqueezing:\n{a}\n{a.shape}\n')

# Adding a new dimension
a.unsqueeze_(0)
print(f'Tensor `a` after unsqueezing:\n{a}]\n{a.shape}')

Tensor `a` before unsqueezing:
tensor([[[0.5472, 0.0062, 0.9516],
         [0.0753, 0.8860, 0.5832],
         [0.3376, 0.8090, 0.5779]],

        [[0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104],
         [0.9464, 0.7890, 0.2814]],

        [[0.7886, 0.5895, 0.7539],
         [0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440]]])
torch.Size([3, 3, 3])

Tensor `a` after unsqueezing:
tensor([[[[0.5472, 0.0062, 0.9516],
          [0.0753, 0.8860, 0.5832],
          [0.3376, 0.8090, 0.5779]],

         [[0.9040, 0.5547, 0.3423],
          [0.6343, 0.3644, 0.7104],
          [0.9464, 0.7890, 0.2814]],

         [[0.7886, 0.5895, 0.7539],
          [0.1952, 0.0050, 0.3068],
          [0.1165, 0.9103, 0.6440]]]])]
torch.Size([1, 3, 3, 3])


In [22]:
b = torch.rand(1, 1, 1, 1, 1)
print(f'Tensor `b` before squeezing:\n{b}\n{b.shape}\n')

# Removing a dimension with size 1
b.squeeze_(0)
print(f'Tensor `b` after squeezing:\n{b}\n{b.shape}')

Tensor `b` before squeezing:
tensor([[[[[0.7071]]]]])
torch.Size([1, 1, 1, 1, 1])

Tensor `b` after squeezing:
tensor([[[[0.7071]]]])
torch.Size([1, 1, 1, 1])


In [23]:
# Create a three-dimensional tensor
output3d = torch.rand(6, 20, 20)

# Reshape the tensor to 1-dim
input1d = output3d.reshape(6 * 20 * 20)

print(f'{output3d.shape} is converted to {input1d.shape}')
# Note: Any changes made to `output3d` will be reflected on `input1d`

torch.Size([6, 20, 20]) is converted to torch.Size([2400])


## Using NumPy with PyTorch Tensors

NumPy operations work with PyTorch tensors effectively.


In [24]:
# Define a NumPy array
numpy_array = np.ones((2, 3))

# Create a tensor from the array
pytorch_tensor = torch.from_numpy(numpy_array)

numpy_array, pytorch_tensor

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64))

In [25]:
# The reverse procedure is defined here
pytorch_rand = torch.rand(2, 3)
numpy_rand = pytorch_rand.numpy()

pytorch_rand, numpy_array

(tensor([[0.8983, 0.8597, 0.7895],
         [0.1101, 0.8894, 0.4522]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))